services:
  backend:
    build:
      context: ./backend
    container_name: backend
    image: my-backend
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5001:5001"
    networks:
      - my-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ""
    container_name: frontend
    image: my-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - my-net

networks:
  my-net:
    name: my-net
    external: true
