name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Backend
      - name: Install backend deps
        run: |
          cd backend
          npm install

      - name: Check backend syntax
        run: |
          find backend -name "*.js" -exec node --check {} \;

      # Frontend
      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Deploy
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Deploy to Vercel
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
